### ISSUE TITLE
Method to get listings for an item

### ISSUE THREAD

**Issue by srg-n** [Nicklason/node-bptf-listings#2]
A method to get buy/sell listings for a specific item would be great

**Comment by Nicklason** [comment]
It is technically already there https://github.com/Nicklason/node-bptf-listings/blob/master/lib/helpers.js#L121

**Comment by Nicklason** [comment]
I’ve added it to v4, please see the examples: https://github.com/Nicklason/node-bptf-listings/blob/master/examples/search.js
